# Generated by Django 3.1.14 on 2022-06-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemongeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemongeo',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name=' Покемон'),
        ),
    ]
