# Generated by Django 3.1.14 on 2022-06-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemongeo_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemongeo',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name=' Покемон'),
        ),
    ]
