# Generated by Django 3.1.14 on 2022-07-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20220630_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=6, verbose_name=' Широта')),
                ('longitude', models.FloatField(max_length=6, verbose_name=' Долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='Появился в')),
                ('disappeared_at', models.DateTimeField(verbose_name='Исчез в')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень')),
                ('health', models.PositiveSmallIntegerField(default=100, verbose_name='Здоровье')),
                ('strength', models.PositiveSmallIntegerField(default=10, verbose_name='Атака')),
                ('defence', models.PositiveSmallIntegerField(default=10, verbose_name='Защита')),
                ('stamina', models.PositiveSmallIntegerField(default=10, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
        migrations.DeleteModel(
            name='PokemonGeo',
        ),
    ]
