# Generated by Django 3.1.14 on 2022-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20220701_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(max_length=255, null=True, verbose_name='Название на японском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название на русском'),
        ),
    ]
