# Generated by Django 3.1.14 on 2022-07-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_pokemonelementtype_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='element_type',
            new_name='elements',
        ),
    ]
